service: replaceme-myslsservice

plugins:
- serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x

# After adding a few functions and associated dependencies, individual function
# packages can be created to avoid a single massive zip file.
# This comes at the cost of potential memory issues at build time:
# https://github.com/serverless-heaven/serverless-webpack/issues/299
# package:
#   individually: true

custom:
  webpack:
    excludeFiles:
      - "src/**/*.test.ts"
      - "src/**/__mocks__/*.ts"
    # We could exclude aws-sdk here to trim down the deployment package via
    # webpack-node-externals (see webpack.config.js), but instead we'll
    # include it so the sdk version used is predictable.
    # includeModules:
    #   forceExclude:
    #     - aws-sdk

functions:
  helloWorld:
    handler: src/helloWorld.handler
    events:
      - http:
          path: hello-world
          method: get
          cors: true
